feat: 게시글 navbar 사이즈별  컴포넌트 퍼블리싱 및 마이페이지 , 채팅 1차 퍼블리싱
N-NProject/frontend pull request #10
Opened 2024-05-09 15:54 UTC by penloo

2024-05-09 15:58 UTC, baekjiyun approved these changes
수고하셨습니당!

2024-05-09 16:25 UTC, Kimyebin00 requested changes
사용자 정의 컴포넌트는 대문자로 시작해야 되는 걸로 알고 있어요! nav나 page 다 소문자로 시작하더라구요. 이것들이랑 오타만 수정해주시면 될 거 같아요. 수고하셨습니다👍🏻

2024-05-09 16:25 UTC, Kimyebin00 commented on my-app/src/app/mypage/page.tsx
> +import thumnail from "../assets/mypage/thumnail.svg";
thumnail -> thumbnail 오타여!! 밑에 다른 코드들도 고쳐주시믄 돼요

2024-05-11 02:55 UTC, penloo commented on my-app/src/app/mypage/page.tsx
> +import thumnail from "../assets/mypage/thumnail.svg";
고쳤습니다! 머지하게 한번만 부탁드려용~

2024-05-12 11:23 UTC, Kimyebin00 approved these changes
수고하셨습니다!

2024-05-12 11:23 UTC, merged